backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog" # Název sekce v adminu
    label: "Příspěvky" # Titulek v adminu
    folder: "content/posts" # Kam se mají soubory ukládat
    create: true # Povolí vytváření nových příspěvků
    slug: "{{slug}}" # Název souboru (např. muj-prvni-clanek.md)
    fields: # Co všechno u příspěvku vyplníš
      - {label: "Titulek", name: "title", widget: "string"}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Obrázek", name: "image", widget: "image", required: false}
      - {label: "Obsah", name: "body", widget: "markdown"}